global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /monitoring/metrics
    static_configs:
      - targets:
          - host.docker.internal:8080 # Change to a valid endpoint to e20 apis