version: "3.8"
name: "e20-dev-env"

services:
  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    restart: no
    environment:
      POSTGRES_DB: e20devdb
      POSTGRES_USER: e20DevUser
      POSTGRES_PASSWORD: e20DevPassword
    volumes:
      - e20-dev-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - e20-dev-postgres-network
  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: no
    ports:
      - "8081:8080"
    networks:
      - e20-dev-postgres-network
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: no
    volumes:
      - e20-dev-redis:/data
    ports:
      - "6379:6379"
    networks:
      - e20-dev-redis-network
  redis-insight:
    image: redislabs/redisinsight
    container_name: ${COMPOSE_PROJECT_NAME}_redis-insight
    restart: no
    ports:
      - "8082:8001"
    networks:
      - e20-dev-redis-network
  prometheus:
    image: prom/prometheus
    container_name: ${COMPOSE_PROJECT_NAME}_prometheus
    restart: no
    ports:
      - "9090:9090"
    volumes:
      - "../prometheus/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml"
    networks:
      - e20-dev-monitor-net
  grafana:
    image: grafana/grafana
    container_name: ${COMPOSE_PROJECT_NAME}_grafana
    restart: no
    ports:
      - "3000:3000"
    volumes:
      - e20-dev-grafana-storage:/var/lib/grafana
    networks:
      - e20-dev-monitor-net

volumes:
  e20-dev-redis: {}
  e20-dev-pgdata: {}
  e20-dev-grafana-storage: {}

networks:
  e20-dev-redis-network:
    name: e20-dev-redis-network
  e20-dev-postgres-network:
    name: e20-dev-postgres-network
  e20-dev-monitor-net:
    name: e20-dev-monitor-net