version: "3.8"
name: "e20-dev-environment"
services:
  e20-postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: e20devdb
      POSTGRES_USER: e20DevUser
      POSTGRES_PASSWORD: e20DevPassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  e20-adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - postgres-network
  e20-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - redis-network
  e20-redis-insight:
    image: redislabs/redisinsight
    restart: unless-stopped
    ports:
      - "8082:8001"
    networks:
      - redis-network
  e20-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "../prometheus/prometheus-monitoring.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor-net
  e20-grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net

volumes:
  redis: {}
  pgdata: {}
  grafana-storage: {}

networks:
  redis-network:
    name: redis-network
  postgres-network:
    name: postgres-network
  monitor-net:
    name: monitor-net