version: "3.8"
services:
  e20:
    image: eu.gcr.io/e-20-408110/e-20-api:latest
    container_name: "e20-api"
    env_file:
      - .env
    ports:
      - "8080:${PORT}"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net

volumes:
  grafana-storage: {}

networks:
  monitor-net:
    name: monitor-net
